### ISSUE TITLE
Replace maximum derivative dot indicator with a vertical line

### ISSUE THREAD

**Issue by cwade6** [oss-slu/MeltWin2.0#75]

**Comment by shlokpat6** [comment]
On the new implementation of the analysis graphs, there a dot on the derivative curve is colored to indicate the maximum derivative. Unfortunately, with the sheer number of dots on the graph, this colored dot is almost unnoticeable. An alternative implementation could be to use a faded, dotted, vertical line that would be more prominent than a single colored point but also not distract the user from the rest of the information on the graph.
